[package]
name = "relay"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
futures-util.workspace = true
axum = { version = "0.7", features = ["ws"] }
getrandom = "0.2"
async-trait = "0.1"
bytes = "1"
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }

[dev-dependencies]
tokio-tungstenite = "0.23"
